In [1]:
import os
os.chdir("../")

In [2]:
import pandas
import numpy as np
import os
import datetime

import os
import wget

import zipfile

In [3]:
from storage.har_datasets import MHEALTHDataset

In [6]:
ds = MHEALTHDataset("./datasets/MHEALTH/", sensor="ecg", wsize=64, wstride=1, normalize=False, label_mapping=None)

In [9]:
("acc", "ecg") in ("", "acc", "ecg", "gyro", "mag")

False

In [7]:
ds.STS.shape

(2, 1215745)

In [22]:
np.percentile(ds.STS, 90, axis=1)

array([-3.7563 ,  2.1415 ,  2.6134 ,  4.6847 , -5.47074,  3.44806,
        1.0529 ,  2.7011 ,  7.4073 ])

In [10]:
ds.mean

array([[-8.52236112],
       [-0.21400133],
       [-1.05594958],
       [ 1.49419996],
       [-9.69287848],
       [-0.95480564],
       [-3.71341308],
       [-5.8055262 ],
       [ 2.3938804 ]])

In [14]:
ds[0][0]

array([[-9.65542662e-02, -9.01304499e-02, -7.89229406e-02,
        -8.91017761e-02, -9.24683450e-02, -9.12814136e-02,
        -6.01262643e-02, -8.92888077e-02, -8.58574971e-02,
        -7.99228404e-02, -5.72776291e-02, -8.64401725e-02,
        -6.95281992e-02, -8.40447292e-02, -5.41124788e-02,
        -8.13543515e-02, -8.17499953e-02, -8.18507046e-02,
        -9.13965100e-02, -8.47137269e-02, -9.80217449e-02,
        -9.73527473e-02, -1.09891058e-01, -7.08949686e-02,
        -1.03229856e-01, -8.53107893e-02, -7.02115839e-02,
        -9.40581136e-02, -9.41444359e-02, -7.49808899e-02,
        -9.02671268e-02, -9.06411901e-02, -9.90504188e-02,
        -9.23244745e-02, -8.12824163e-02, -7.57649839e-02,
        -8.06709668e-02, -8.50014678e-02, -6.74204969e-02,
        -6.90606202e-02, -6.80894946e-02, -9.41875970e-02,
        -8.08220308e-02, -8.38864717e-02, -8.75911362e-02,
        -8.44044054e-02, -7.62973046e-02, -7.79662020e-02,
        -6.20613220e-02, -8.85334877e-02, -9.67269108e-0

In [12]:
ds[0][0]

array([[ -9.8646  ,  -9.7753  ,  -9.6195  ,  -9.761   ,  -9.8078  ,
         -9.7913  ,  -9.3582  ,  -9.7636  ,  -9.7159  ,  -9.6334  ,
         -9.3186  ,  -9.724   ,  -9.4889  ,  -9.6907  ,  -9.2746  ,
         -9.6533  ,  -9.6588  ,  -9.6602  ,  -9.7929  ,  -9.7     ,
         -9.885   ,  -9.8757  , -10.05    ,  -9.5079  ,  -9.9574  ,
         -9.7083  ,  -9.4984  ,  -9.8299  ,  -9.8311  ,  -9.5647  ,
         -9.7772  ,  -9.7824  ,  -9.8993  ,  -9.8058  ,  -9.6523  ,
         -9.5756  ,  -9.6438  ,  -9.704   ,  -9.4596  ,  -9.4824  ,
         -9.4689  ,  -9.8317  ,  -9.6459  ,  -9.6885  ,  -9.74    ,
         -9.6957  ,  -9.583   ,  -9.6062  ,  -9.3851  ,  -9.7531  ,
         -9.867   ,  -9.8462  ,  -9.782   ,  -9.6418  ,  -9.6814  ,
         -9.44    ,  -9.9502  ,  -9.76    ,  -9.7533  ,  -9.6617  ,
         -9.6923  ,  -9.6559  ,  -9.5249  ,  -9.4832  ],
       [  0.2986  ,   0.38106 ,   0.16943 ,   0.16938 ,  -0.013582,
          0.16961 ,   0.23511 ,   0.29939 ,   0.44389 ,   0